[tool.black]
line-length = 90

[tool.isort]
profile = "black"
line_length = 90

[tool.flakeheaven]
format = "grouped"
max_line_length = 95

[tool.flakeheaven.plugins]
pycodestyle = ["+*", "-E501", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
exclude = [
    "migrations",
]

[tool.pytest.ini_options]
minversion = "7.0"
